"""Realistic reference data used by the seeder."""

LOCALITIES: list[dict] = [
    {"name": "Shivajinagar", "lat": 18.5308, "lng": 73.8478, "pincode": "411005"},
    {"name": "Hinjewadi", "lat": 18.5913, "lng": 73.7389, "pincode": "411057"},
    {"name": "Baner", "lat": 18.5590, "lng": 73.7868, "pincode": "411045"},
    {"name": "Wakad", "lat": 18.5985, "lng": 73.7625, "pincode": "411057"},
    {"name": "Pimpri", "lat": 18.6298, "lng": 73.7997, "pincode": "411018"},
    {"name": "Chinchwad", "lat": 18.6472, "lng": 73.7998, "pincode": "411033"},
    {"name": "Hadapsar", "lat": 18.5089, "lng": 73.9260, "pincode": "411028"},
    {"name": "Katraj", "lat": 18.4483, "lng": 73.8577, "pincode": "411046"},
    {"name": "Warje", "lat": 18.4837, "lng": 73.8043, "pincode": "411058"},
    {"name": "Kondhwa", "lat": 18.4676, "lng": 73.8918, "pincode": "411048"},
    {"name": "Sinhagad Road", "lat": 18.4680, "lng": 73.8280, "pincode": "411041"},
    {"name": "Bhosari", "lat": 18.6298, "lng": 73.8467, "pincode": "411039"},
    {"name": "Aundh", "lat": 18.5590, "lng": 73.8077, "pincode": "411007"},
    {"name": "Yerwada", "lat": 18.5510, "lng": 73.8830, "pincode": "411006"},
    {"name": "City Center", "lat": 18.5204, "lng": 73.8567, "pincode": "411001"},
    {"name": "Khed Shivapur", "lat": 18.3555, "lng": 73.8300, "pincode": "412205"},
    {"name": "Wagholi", "lat": 18.5793, "lng": 73.9800, "pincode": "412207"},
    {"name": "Chakan", "lat": 18.7606, "lng": 73.8636, "pincode": "410501"},
    {"name": "Mulshi", "lat": 18.5211, "lng": 73.5117, "pincode": "412108"},
    {"name": "Saswad", "lat": 18.3466, "lng": 74.0330, "pincode": "412301"},
]

HOSPITALS: list[dict] = [
    {
        "name": "Sassoon General Hospital",
        "facility_type": "district_hospital",
        "locality": "City Center",
        "address": "Jai Prakash Narayan Road, Near Railway Station",
        "phone": "020-26128000",
        "total_beds": 1296,
        "icu_beds": 120,
        "has_blood_bank": True,
        "open_24x7": True,
        "services": "Emergency, Trauma, Surgery, Obstetrics, Paediatrics, Dialysis, Blood Bank, Burns Unit",
        "rating": 4.3,
    },
    {
        "name": "Aundh District Hospital",
        "facility_type": "district_hospital",
        "locality": "Aundh",
        "address": "Aundh Camp Road, Aundh",
        "phone": "020-25887888",
        "total_beds": 320,
        "icu_beds": 40,
        "has_blood_bank": True,
        "open_24x7": True,
        "services": "Emergency, General Medicine, Orthopaedics, Obstetrics, Paediatrics, Blood Bank",
        "rating": 4.1,
    },
    {
        "name": "YCM Hospital (PCMC)",
        "facility_type": "district_hospital",
        "locality": "Pimpri",
        "address": "Yashwantrao Chavan Memorial Hospital, Sant Tukaram Nagar, Pimpri",
        "phone": "020-27423333",
        "total_beds": 750,
        "icu_beds": 90,
        "has_blood_bank": True,
        "open_24x7": True,
        "services": "Emergency, Cardiology, Nephrology, Neurology, Obstetrics, NICU, Blood Bank",
        "rating": 4.2,
    },
    {
        "name": "Kamla Nehru Hospital (PMC)",
        "facility_type": "community_health_center",
        "locality": "Shivajinagar",
        "address": "Mangalwar Peth, Near Shivajinagar",
        "phone": "020-26051234",
        "total_beds": 250,
        "icu_beds": 30,
        "open_24x7": True,
        "services": "Emergency, Infectious Diseases, General Medicine, Isolation Ward",
        "rating": 4.0,
    },
    {
        "name": "Rajiv Gandhi Hospital, Yerwada",
        "facility_type": "community_health_center",
        "locality": "Yerwada",
        "address": "Alandi Road, Yerwada",
        "phone": "020-26681234",
        "total_beds": 180,
        "icu_beds": 20,
        "open_24x7": True,
        "services": "Emergency, General Surgery, Obstetrics, Paediatrics",
        "rating": 3.9,
    },
    {
        "name": "Hadapsar Urban Health Centre",
        "facility_type": "urban_health_center",
        "locality": "Hadapsar",
        "address": "Gadital, Hadapsar",
        "phone": "020-26993344",
        "total_beds": 40,
        "icu_beds": 4,
        "services": "OPD, Immunisation, Antenatal Care, NCD Clinic, Pharmacy",
        "rating": 4.0,
    },
    {
        "name": "Katraj Urban Health Centre",
        "facility_type": "urban_health_center",
        "locality": "Katraj",
        "address": "Katraj Chowk, Satara Road",
        "phone": "020-24367788",
        "total_beds": 30,
        "icu_beds": 2,
        "services": "OPD, Immunisation, TB DOTS Centre, Antenatal Care",
        "rating": 3.8,
    },
    {
        "name": "Warje-Malwadi Primary Health Centre",
        "facility_type": "phc",
        "locality": "Warje",
        "address": "Malwadi Road, Warje",
        "phone": "020-25230011",
        "total_beds": 20,
        "icu_beds": 0,
        "services": "OPD, Immunisation, Maternal Health, Basic Lab, Pharmacy",
        "rating": 3.9,
    },
    {
        "name": "Kondhwa Primary Health Centre",
        "facility_type": "phc",
        "locality": "Kondhwa",
        "address": "Kondhwa Khurd, NIBM Road",
        "phone": "020-26831199",
        "total_beds": 18,
        "icu_beds": 0,
        "services": "OPD, Immunisation, ANC, NCD Screening",
        "rating": 3.7,
    },
    {
        "name": "Hinjewadi Primary Health Centre",
        "facility_type": "phc",
        "locality": "Hinjewadi",
        "address": "Phase 1, Hinjewadi Village Road",
        "phone": "020-22934455",
        "total_beds": 22,
        "icu_beds": 2,
        "services": "OPD, Immunisation, Occupational Health, Pharmacy",
        "rating": 4.1,
    },
    {
        "name": "Wakad Primary Health Centre",
        "facility_type": "phc",
        "locality": "Wakad",
        "address": "Datta Mandir Road, Wakad",
        "phone": "020-27271122",
        "total_beds": 20,
        "icu_beds": 0,
        "services": "OPD, Immunisation, ANC, DOTS",
        "rating": 3.9,
    },
    {
        "name": "Bhosari Sub-Centre",
        "facility_type": "sub_center",
        "locality": "Bhosari",
        "address": "MIDC Road, Bhosari",
        "phone": "020-27110099",
        "total_beds": 6,
        "icu_beds": 0,
        "has_emergency": False,
        "services": "ANC, Immunisation, ASHA coordination, Basic first aid",
        "rating": 3.6,
    },
    {
        "name": "Sinhagad Road Sub-Centre",
        "facility_type": "sub_center",
        "locality": "Sinhagad Road",
        "address": "Vadgaon Budruk, Sinhagad Road",
        "phone": "020-24356677",
        "total_beds": 6,
        "icu_beds": 0,
        "has_emergency": False,
        "services": "ANC, Immunisation, Family Planning",
        "rating": 3.7,
    },
    {
        "name": "Chakan Rural Hospital",
        "facility_type": "community_health_center",
        "locality": "Chakan",
        "address": "Nashik Highway, Chakan",
        "phone": "02135-249900",
        "total_beds": 100,
        "icu_beds": 10,
        "open_24x7": True,
        "services": "Emergency, Obstetrics, General Medicine, Snake-bite management",
        "rating": 3.8,
    },
    {
        "name": "Saswad Rural Hospital",
        "facility_type": "community_health_center",
        "locality": "Saswad",
        "address": "Purandar Taluka, Saswad",
        "phone": "02115-222333",
        "total_beds": 80,
        "icu_beds": 8,
        "open_24x7": True,
        "services": "Emergency, Obstetrics, Paediatrics, Trauma stabilisation",
        "rating": 3.7,
    },
]

SPECIALIZATIONS = [
    "General Medicine",
    "Obstetrics & Gynaecology",
    "Paediatrics",
    "General Surgery",
    "Orthopaedics",
    "Cardiology",
    "Pulmonology",
    "Dermatology",
    "Ophthalmology",
    "ENT",
    "Psychiatry",
    "Endocrinology",
    "Neurology",
    "Community Medicine",
]

MEDICINES: list[dict] = [
    ("Paracetamol", "Acetaminophen", "Analgesic", "Tablet", "500mg", 1.2),
    ("Amoxicillin", "Amoxicillin", "Antibiotic", "Capsule", "500mg", 4.5),
    ("Azithromycin", "Azithromycin", "Antibiotic", "Tablet", "500mg", 12.0),
    ("Metformin", "Metformin HCl", "Antidiabetic", "Tablet", "500mg", 2.1),
    ("Amlodipine", "Amlodipine besylate", "Antihypertensive", "Tablet", "5mg", 1.8),
    ("Telmisartan", "Telmisartan", "Antihypertensive", "Tablet", "40mg", 3.4),
    ("Ferrous Sulphate + Folic Acid", "IFA", "Supplement", "Tablet", "100mg+500mcg", 0.9),
    ("Calcium + Vitamin D3", "Calcium carbonate", "Supplement", "Tablet", "500mg", 2.5),
    ("ORS Sachet", "Oral Rehydration Salts", "Rehydration", "Sachet", "21.8g", 8.0),
    ("Zinc Sulphate", "Zinc", "Supplement", "Dispersible Tablet", "20mg", 1.5),
    ("Albendazole", "Albendazole", "Anthelmintic", "Tablet", "400mg", 3.0),
    ("Chloroquine", "Chloroquine phosphate", "Antimalarial", "Tablet", "250mg", 2.8),
    ("Artesunate", "Artesunate", "Antimalarial", "Injection", "60mg", 95.0),
    ("Salbutamol", "Salbutamol sulphate", "Bronchodilator", "Inhaler", "100mcg", 145.0),
    ("Budesonide", "Budesonide", "Corticosteroid", "Inhaler", "200mcg", 320.0),
    ("Cetirizine", "Cetirizine HCl", "Antihistamine", "Tablet", "10mg", 1.1),
    ("Pantoprazole", "Pantoprazole sodium", "Antacid", "Tablet", "40mg", 3.2),
    ("Ondansetron", "Ondansetron", "Antiemetic", "Tablet", "4mg", 2.4),
    ("Ibuprofen", "Ibuprofen", "NSAID", "Tablet", "400mg", 1.6),
    ("Diclofenac", "Diclofenac sodium", "NSAID", "Gel", "1%", 68.0),
    ("Insulin Human", "Regular insulin", "Antidiabetic", "Injection", "40IU/ml", 180.0),
    ("Atorvastatin", "Atorvastatin calcium", "Statin", "Tablet", "10mg", 4.2),
    ("Isoniazid", "Isoniazid", "Anti-TB", "Tablet", "300mg", 2.0),
    ("Rifampicin", "Rifampicin", "Anti-TB", "Capsule", "450mg", 6.5),
    ("Ethambutol", "Ethambutol HCl", "Anti-TB", "Tablet", "800mg", 5.0),
    ("Misoprostol", "Misoprostol", "Obstetric", "Tablet", "200mcg", 22.0),
    ("Oxytocin", "Oxytocin", "Obstetric", "Injection", "5IU", 18.0),
    ("Magnesium Sulphate", "MgSO4", "Obstetric", "Injection", "50%", 26.0),
    ("Tetanus Toxoid", "TT", "Vaccine", "Injection", "0.5ml", 15.0),
    ("Anti-Snake Venom", "Polyvalent ASV", "Antivenom", "Injection", "10ml", 620.0),
    ("Adrenaline", "Epinephrine", "Emergency", "Injection", "1mg/ml", 24.0),
    ("Dexamethasone", "Dexamethasone", "Corticosteroid", "Injection", "4mg/ml", 12.0),
    ("Ceftriaxone", "Ceftriaxone sodium", "Antibiotic", "Injection", "1g", 42.0),
    ("Metronidazole", "Metronidazole", "Antibiotic", "Tablet", "400mg", 1.9),
    ("Vitamin A Solution", "Retinol", "Supplement", "Syrup", "1 lakh IU", 32.0),
]

VACCINES_CHILD: list[tuple[str, str, int]] = [
    ("BCG", "Birth dose", 0),
    ("Hepatitis B", "Birth dose", 0),
    ("OPV", "Zero dose", 0),
    ("Pentavalent", "Dose 1", 42),
    ("Rotavirus", "Dose 1", 42),
    ("fIPV", "Dose 1", 42),
    ("Pentavalent", "Dose 2", 70),
    ("Rotavirus", "Dose 2", 70),
    ("Pentavalent", "Dose 3", 98),
    ("Rotavirus", "Dose 3", 98),
    ("fIPV", "Dose 2", 98),
    ("Measles-Rubella", "Dose 1", 270),
    ("JE", "Dose 1", 270),
    ("Vitamin A", "Dose 1", 270),
    ("DPT", "Booster 1", 480),
    ("Measles-Rubella", "Dose 2", 480),
    ("OPV", "Booster", 480),
    ("DPT", "Booster 2", 1825),
]

VACCINES_ADULT = [
    ("Td", "Booster"),
    ("COVID-19 Precaution Dose", "Booster"),
    ("Influenza", "Annual"),
    ("Hepatitis B", "Dose 3"),
    ("Rabies (post-exposure)", "Dose 1"),
]

DISEASES = [
    ("Dengue", "high"),
    ("Malaria", "moderate"),
    ("Chikungunya", "moderate"),
    ("Tuberculosis", "high"),
    ("Gastroenteritis", "moderate"),
    ("Typhoid", "moderate"),
    ("Leptospirosis", "high"),
    ("Hepatitis A", "moderate"),
    ("Influenza-like Illness", "low"),
    ("Hypertension (new detections)", "low"),
]

CHRONIC_CONDITIONS = [
    "Type 2 Diabetes",
    "Hypertension",
    "Asthma",
    "Hypothyroidism",
    "Anaemia",
    "Chronic Kidney Disease",
    "Arthritis",
]

ALLERGIES = ["Penicillin", "Sulpha drugs", "Dust", "Pollen", "Peanuts", "Lactose", "Aspirin"]

FIRST_NAMES_M = [
    "Aarav", "Sagar", "Rohit", "Ganesh", "Mahesh", "Nilesh", "Prashant", "Sandeep", "Vishal",
    "Amol", "Kiran", "Dattatray", "Balu", "Santosh", "Yogesh", "Pravin", "Sachin", "Manoj",
    "Sunil", "Rahul", "Ajinkya", "Omkar", "Tushar", "Nikhil", "Swapnil",
]

FIRST_NAMES_F = [
    "Aditi", "Sunita", "Kavita", "Manisha", "Pooja", "Snehal", "Vaishali", "Rekha", "Shraddha",
    "Anita", "Sarika", "Rupali", "Jyoti", "Madhuri", "Archana", "Priyanka", "Trupti", "Nanda",
    "Shubhangi", "Deepali", "Ashwini", "Komal", "Sayali", "Prerana", "Mayuri",
]

SURNAMES = [
    "Jadhav", "Pawar", "Shinde", "Kadam", "More", "Patil", "Deshmukh", "Bhosale", "Gaikwad",
    "Sawant", "Kulkarni", "Joshi", "Chavan", "Salunkhe", "Thorat", "Dhumal", "Wagh", "Nikam",
    "Bhosle", "Mane", "Kale", "Shelar", "Ghule", "Lokhande", "Kamble",
]

WATER_SOURCES = ["Municipal tap", "Borewell", "Community well", "Tanker supply", "Hand pump"]

APPOINTMENT_REASONS = [
    "Fever and body ache for 3 days",
    "Routine antenatal check-up",
    "Blood pressure follow-up",
    "Diabetes review and HbA1c report",
    "Child immunisation consultation",
    "Persistent cough for 2 weeks",
    "Skin rash and itching",
    "Knee pain while walking",
    "Chest discomfort on exertion",
    "Follow-up after discharge",
    "Anaemia treatment review",
    "Eye check-up for blurred vision",
]

LAB_PANELS: list[dict] = [
    {
        "title": "Complete Blood Count (CBC)",
        "fields": {"Haemoglobin (g/dL)": (9.0, 15.5), "WBC (/µL)": (4000, 12000), "Platelets (/µL)": (140000, 420000)},
        "normal": {"Haemoglobin (g/dL)": (12, 15.5), "WBC (/µL)": (4000, 11000), "Platelets (/µL)": (150000, 410000)},
    },
    {
        "title": "Fasting Blood Sugar",
        "fields": {"FBS (mg/dL)": (78, 190), "HbA1c (%)": (4.8, 9.4)},
        "normal": {"FBS (mg/dL)": (70, 110), "HbA1c (%)": (4.0, 5.7)},
    },
    {
        "title": "Lipid Profile",
        "fields": {"Total Cholesterol (mg/dL)": (140, 260), "LDL (mg/dL)": (70, 180), "HDL (mg/dL)": (30, 65)},
        "normal": {"Total Cholesterol (mg/dL)": (0, 200), "LDL (mg/dL)": (0, 100), "HDL (mg/dL)": (40, 100)},
    },
    {
        "title": "Liver Function Test",
        "fields": {"SGPT (U/L)": (14, 90), "SGOT (U/L)": (12, 85), "Bilirubin (mg/dL)": (0.3, 2.2)},
        "normal": {"SGPT (U/L)": (0, 45), "SGOT (U/L)": (0, 40), "Bilirubin (mg/dL)": (0, 1.2)},
    },
    {
        "title": "Thyroid Profile",
        "fields": {"TSH (µIU/mL)": (0.3, 9.0), "T3 (ng/dL)": (70, 200), "T4 (µg/dL)": (4.0, 12.5)},
        "normal": {"TSH (µIU/mL)": (0.4, 4.0), "T3 (ng/dL)": (80, 200), "T4 (µg/dL)": (4.5, 12.0)},
    },
    {
        "title": "Malaria & Dengue Panel",
        "fields": {"Malaria antigen": (0, 1), "Dengue NS1": (0, 1), "Platelets (/µL)": (60000, 300000)},
        "normal": {"Malaria antigen": (0, 0), "Dengue NS1": (0, 0), "Platelets (/µL)": (150000, 410000)},
    },
]
